using Unity.Entities;

namespace Godgame.Prayer
{
    /// <summary>
    /// Divine currency pool - global singleton tracking accumulated worship.
    /// Prayer power is generated by villagers and consumed by miracles.
    /// See Docs/Concepts/Core/Prayer_Power.md for full spec.
    /// </summary>
    public struct PrayerPowerPool : IComponentData
    {
        /// <summary>
        /// Current prayer power available for miracles.
        /// </summary>
        public float CurrentPrayer;

        /// <summary>
        /// Maximum prayer power cap (prevents infinite hoarding).
        /// Default: 50,000
        /// </summary>
        public float MaxPrayer;

        /// <summary>
        /// Computed generation rate (prayer/second) from all sources.
        /// Updated each frame by PrayerGenerationSystem.
        /// </summary>
        public float GenerationRate;

        /// <summary>
        /// Total prayer generated this session (for telemetry).
        /// </summary>
        public float TotalGenerated;

        /// <summary>
        /// Total prayer consumed this session (for telemetry).
        /// </summary>
        public float TotalConsumed;

        /// <summary>
        /// Create a default prayer pool with standard settings.
        /// </summary>
        public static PrayerPowerPool Default => new PrayerPowerPool
        {
            CurrentPrayer = 1000f,  // Start with some prayer
            MaxPrayer = 50000f,
            GenerationRate = 0f,
            TotalGenerated = 0f,
            TotalConsumed = 0f
        };

        /// <summary>
        /// Attempt to consume prayer power for a miracle.
        /// </summary>
        /// <param name="amount">Prayer cost</param>
        /// <returns>True if consumed, false if insufficient</returns>
        public bool TryConsume(float amount)
        {
            if (CurrentPrayer >= amount)
            {
                CurrentPrayer -= amount;
                TotalConsumed += amount;
                return true;
            }
            return false;
        }

        /// <summary>
        /// Add prayer power (capped at max).
        /// </summary>
        /// <param name="amount">Prayer to add</param>
        /// <returns>Actual amount added (may be less if capped)</returns>
        public float Add(float amount)
        {
            float space = MaxPrayer - CurrentPrayer;
            float added = amount < space ? amount : space;
            CurrentPrayer += added;
            TotalGenerated += added;
            return added;
        }

        /// <summary>
        /// Get fill percentage (0-1).
        /// </summary>
        public float FillRatio => MaxPrayer > 0 ? CurrentPrayer / MaxPrayer : 0f;
    }

    /// <summary>
    /// Per-entity component marking villagers (or buildings) that generate prayer.
    /// Attach to villagers to contribute to the global prayer pool.
    /// </summary>
    public struct PrayerGenerator : IComponentData
    {
        /// <summary>
        /// Base prayer generation rate (prayer/second).
        /// Default: 1.0 for villagers
        /// </summary>
        public float BaseRate;

        /// <summary>
        /// Multiplier from mood, temples, alignment, etc.
        /// Default: 1.0 (no bonus)
        /// </summary>
        public float Multiplier;

        /// <summary>
        /// Whether this generator is currently active.
        /// Disabled villagers (dead, unconscious) don't generate prayer.
        /// </summary>
        public bool IsActive;

        /// <summary>
        /// Computed effective rate (BaseRate * Multiplier).
        /// </summary>
        public float EffectiveRate => IsActive ? BaseRate * Multiplier : 0f;

        /// <summary>
        /// Create a default prayer generator for a villager.
        /// </summary>
        public static PrayerGenerator DefaultVillager => new PrayerGenerator
        {
            BaseRate = 1.0f,
            Multiplier = 1.0f,
            IsActive = true
        };

        /// <summary>
        /// Create a prayer generator for a temple.
        /// Temples don't generate prayer directly but could boost area.
        /// </summary>
        public static PrayerGenerator Temple(float rate) => new PrayerGenerator
        {
            BaseRate = rate,
            Multiplier = 1.0f,
            IsActive = true
        };
    }

    /// <summary>
    /// Configuration singleton for prayer system tuning.
    /// </summary>
    public struct PrayerSystemConfig : IComponentData
    {
        /// <summary>
        /// Global multiplier applied to all prayer generation.
        /// Use for difficulty scaling or events.
        /// </summary>
        public float GlobalMultiplier;

        /// <summary>
        /// Minimum prayer per villager (prevents zero generation).
        /// </summary>
        public float MinPrayerPerVillager;

        /// <summary>
        /// Maximum prayer per villager (prevents exploits).
        /// </summary>
        public float MaxPrayerPerVillager;

        /// <summary>
        /// Whether the pool should cap at MaxPrayer.
        /// If false, prayer can accumulate infinitely.
        /// </summary>
        public bool EnforceCap;

        /// <summary>
        /// Default configuration.
        /// </summary>
        public static PrayerSystemConfig Default => new PrayerSystemConfig
        {
            GlobalMultiplier = 1.0f,
            MinPrayerPerVillager = 0.1f,
            MaxPrayerPerVillager = 10.0f,
            EnforceCap = true
        };
    }

    /// <summary>
    /// Tag component for the prayer pool singleton entity.
    /// </summary>
    public struct PrayerPoolTag : IComponentData { }
}

